using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Scumm.Engine.Resources.Scripts
{
    enum VariableV5 : uint
    {
        VAR_RESULT          = 0,
	    VAR_EGO             = 1,
	    VAR_CAMERA_POS_X    = 2,
	    VAR_HAVE_MSG        = 3,
        VAR_ROOM            = 4,
	    VAR_OVERRIDE        = 5,
	    VAR_MACHINE_SPEED   = 6,
	    VAR_ME              = 7,
        VAR_NUM_ACTOR       = 8,
	    VAR_CURRENT_LIGHTS  = 9,
	    VAR_CURRENTDRIVE    = 10,
	    VAR_TMR_1           = 11,
        VAR_TMR_2           = 12,
	    VAR_TMR_3           = 13,
	    VAR_MUSIC_TIMER     = 14,
	    VAR_ACTOR_RANGE_MIN = 15,
        VAR_ACTOR_RANGE_MAX = 16,
	    VAR_CAMERA_MIN_X    = 17,
	    VAR_CAMERA_MAX_X    = 18,
	    VAR_TIMER_NEXT      = 19,
        VAR_VIRT_MOUSE_X    = 20,
	    VAR_VIRT_MOUSE_Y    = 21,
	    VAR_ROOM_RESOURCE   = 22,
	    VAR_LAST_SOUND      = 23,
        VAR_CUTSCENEEXIT_KEY= 24,
	    VAR_TALK_ACTOR      = 25,
	    VAR_CAMERA_FAST_X   = 26,
	    VAR_SCROLL_SCRIPT   = 27,
        VAR_ENTRY_SCRIPT    = 28,
        VAR_ENTRY_SCRIPT2   = 29,
        VAR_EXIT_SCRIPT     = 30,
        VAR_EXIT_SCRIPT2    = 31,
        VAR_VERB_SCRIPT     = 32,
	    VAR_SENTENCE_SCRIPT = 33,
	    VAR_INVENTORY_SCRIPT= 34,
	    VAR_CUTSCENE_START_SCRIPT = 35,
        VAR_CUTSCENE_END_SCRIPT   = 36,
	    VAR_CHARINC         = 37,
	    VAR_WALKTO_OBJ      = 38,
        VAR_DEBUGMODE       = 39,
        VAR_HEAPSPACE       = 40,
	    VAR_RESTART_KEY     = 42,
	    VAR_PAUSE_KEY       = 43,
	    VAR_MOUSE_X         = 44,
	    VAR_MOUSE_Y         = 45,
	    VAR_TIMER           = 46,
	    VAR_TIMER_TOTAL     = 47,
	    VAR_SOUNDCARD       = 48,
	    VAR_VIDEOMODE       = 49,
	    VAR_MAINMENU_KEY    = 50,
	    VAR_FIXEDDISK       = 51,
        VAR_CURSORSTATE     = 52,
        VAR_USERPUT         = 53,
	    VAR_SOUNDRESULT     = 56,
	    VAR_TALKSTOP_KEY    = 57,
	    VAR_FADE_DELAY      = 59,
	    VAR_NOSUBTITLES     = 60,
	    VAR_SOUNDPARAM      = 64,
	    VAR_SOUNDPARAM2     = 65,
	    VAR_SOUNDPARAM3     = 66,
	    VAR_INPUTMODE       = 67,
        VAR_MEMORY_PERFORMANCE = 68,
	    VAR_VIDEO_PERFORMANCE  = 69,
	    VAR_ROOM_FLAG       = 70,
	    VAR_GAME_LOADED     = 71,
        VAR_NEW_ROOM        = 72,
        VAR_VERSION         = 75

    };
}
